version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: ${APP_NAME}-mysql
    volumes:
      - ~/DB/${APP_NAME}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
